preset: recommended

enabled:
  - concat_with_spaces
  - dir_constant
  - uppercase_constants
  - declare_strict_types
  - ternary_to_null_coalescing

disabled:
  - braces
  - class_definition
  - concat_without_spaces
  - declare_equal_normalize
  - lowercase_constants
  - include
  - phpdoc_summary
  - no_blank_lines_after_class_opening
  - single_class_element_per_statement
  - alpha_ordered_imports

finder:
  name:
    - "*.php"
