language: php
cache:
  directories:
    - $HOME/.cache/pip
php:
  - '7.0'
  - '7.1'
env:
  - TESTTYPE=server
  - TESTTYPE=client
before_script:
  - sudo apt-get update
  - sudo apt-get install python-pip
  - sudo -H pip install -U pip wheel
  - sudo -H pip install autobahntestsuite
  - phpenv config-rm xdebug.ini
script:
  - php Tests/runner.php $TESTTYPE
notifications:
  email:
    recipients:
      - kevkevm@gmail.com
    on_success: change
    on_failure: always
addons:
  artifacts:
    paths: /tmp/reports/
