language: php
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.cache/pip

php:
  - 7.3
  - 7.4
  - 8.0
  - 8.1
  - nightly

env:
  - $TESTSCRIPT=tests/ClientTest.php $BUFFERTPE=memory
  - $TESTSCRIPT=tests/ClientTest.php $BUFFERTPE=tmpfile
  - $TESTSCRIPT=tests/ServerTest.php $BUFFERTPE=memory
  - $TESTSCRIPT=tests/ServerTest.php $BUFFERTPE=tmpfile
  - $TESTSCRIPT=tests/UpdatesWrapperTest.php

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - sudo apt-get update
  - sudo apt-get install python-pip python-virtualenv
  - virtualenv ~/wstest
  - source ~/wstest/bin/activate
  - pip install autobahntestsuite
  - phpenv config-rm xdebug.ini || true
  - composer install

script:
  - vendor/bin/phpunit $TESTSCRIPT buffertype=$BUFFERTPE

notifications:
  email:
    recipients:
      - admin@kevinmeijer.nl
    on_success: change
    on_failure: always
