language: php
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.cache/pip
php:
  - '7.0'
  - '7.1'
  - '7.2'
env:
  - $TESTCLASS=PHPWebSocket/Client $TESTSCRIPT=tests/ClientTest.php $BUFFERTPE=memory
  - $TESTCLASS=PHPWebSocket/Client $TESTSCRIPT=tests/ClientTest.php $BUFFERTPE=tmpfile
  - $TESTCLASS=PHPWebSocket/Server $TESTSCRIPT=tests/ServerTest.php $BUFFERTPE=memory
  - $TESTCLASS=PHPWebSocket/Server $TESTSCRIPT=tests/ServerTest.php $BUFFERTPE=tmpfile
before_script:
  - sudo apt-get update
  - sudo apt-get install python-pip python-virtualenv
  - virtualenv ~/wstest
  - source ~/wstest/bin/activate
  - pip install autobahntestsuite
#  - sudo -H pip install -U pip wheel
#  - sudo -H pip install autobahntestsuite
  - phpenv config-rm xdebug.ini
  - composer update
script:
  - vendor/bin/phpunit $TESTCLASS $TESTSCRIPT buffertype=$BUFFERTPE
notifications:
  email:
    recipients:
      - admin@kevinmeijer.nl
    on_success: change
    on_failure: always
# addons:
#   artifacts:
#     paths: /tmp/reports/
