language: php
cache:
  directories:
    - $HOME/.cache/pip
php:
  - '7.0'
  - '7.1'
env:
  - $TESTCLASS=PHPWebSocket/Client $TESTSCRIPT=tests/ClientTest.php $BUFFERTPE=memory
  - $TESTCLASS=PHPWebSocket/Client $TESTSCRIPT=tests/ClientTest.php $BUFFERTPE=tmpfile
before_script:
  - sudo apt-get update
  - sudo apt-get install python-pip
  - sudo -H pip install -U pip wheel
  - sudo -H pip install autobahntestsuite
  - phpenv config-rm xdebug.ini
  - composer install
script:
  - vendor/bin/phpunit $TESTCLASS $TESTSCRIPT buffertype=$BUFFERTPE
notifications:
  email:
    recipients:
      - admin@kevinmeijer.nl
    on_success: change
    on_failure: always
# addons:
#   artifacts:
#     paths: /tmp/reports/
